apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: azure-repo-demo-pr
  title: Azure Repository Test - PR
  description: Creates a PR as test
spec:
  owner: wsiqueir
  type: service

  parameters:
    - title: Fill in some steps
      required:        
        - owner
      properties:
        organization:
          title: Organization
          type: string
          description: Organization Name
          default: "wsiqueir"
          ui:field: EntityNamePicker
          ui:autofocus: true
        repoId:
          title: Repository Id
          type: string
          default: "rhdh-tests"
          ui:field: EntityNamePicker
          ui:autofocus: true
        sourceBranch:
          title: Source Branch
          type: string
          default: "test"          
          ui:field: EntityNamePicker
          ui:autofocus: true
        targetBranch:
          title: Target Branch
          type: string
          default: "main"          
          ui:field: EntityNamePicker
          ui:autofocus: true
        project:
          title: Project
          type: string
          default: "rhdh-tests"          
          ui:field: EntityNamePicker
          ui:autofocus: true
        owner:
          title: Owner
          type: string
          description: Select an owner for the Backstage component.
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group

  steps:
    - id: pullRequestAzureRepo
      name: Create a Pull Request to Azure Repo
      action: azure:repo:pr
      input:
        organization:  ${{ parameters.organization }}
        sourceBranch: ${{ parameters.sourceBranch }}
        targetBranch: ${{ parameters.targetBranch }}
        repoId: ${{ parameters.repoId }}
        title: "This is a test Pull Request"
        project: ${{ parameters.project }}
        supportsIterations: false


  output:
    links:
      - title: PR Link
        url: "https://dev.azure.com/${{ parameters.organization }}/${{ parameters.repoId }}/_git/rhdh-tests/pullrequest/${{ steps.pullRequestAzureRepo.output.pullRequestId }}"

