---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  namespace: default
  name: jesuinoMaster
spec:
  profile:
    displayName: Jesuino Master
    picture: https://avatars.githubusercontent.com/u/359820?v=4
  memberOf: [group1, group2]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: jesuino
spec:
  memberOf: [admin]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: williamAntonio
spec:
  memberOf: [admin]
                      
