apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test-plain-psw
  title: test-plain-psw
  description: Test plain password with fields with default value
spec:
  owner: jesuino
  type: service
  parameters:
    - title: Enter a password
      properties:
        password:
          title: Password
          type: string
          default: "123456"
          ui:field: Secret  
  steps:
    - action: debug:log
      id: write-something
      name: Write something in the logs
      input:
        message: hello
  output:
    text:
      - title: Reproducing issue
        content: |
            **Could you see the password?**
