apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test-http-request
  title: Test HTTP Request
  description: Test the plugin HTTP Request
spec:
  owner: jesuino
  type: service
  steps:
    - id: backstage_request
      name: backstage request
      action: http:backstage:request
      input:
        method: 'GET'
        path: '/proxy/quay/api/'
    output:
      getResponse: '{{ steps.backstage_request.output.body }}'
      getCode: '{{ steps.backstage_request.output.code }}'
      getHeaders: '{{ steps.backstage_request.output.headers }}' 
